import { test, expect } from "@playwright/test";

const pages = [
  { path: "/", heading: "astro-ink" },
  { path: "/components", heading: "Components" },
  { path: "/components/alert", heading: "Alert" },
  { path: "/components/accordion", heading: "Accordion" },
  { path: "/components/avatar", heading: "Avatar" },
  { path: "/components/avatar-group", heading: "AvatarGroup" },
  { path: "/components/blockquote", heading: "Blockquote" },
  { path: "/components/card", heading: "Card" },
  { path: "/components/carousel", heading: "Carousel" },
  { path: "/components/code-block", heading: "CodeBlock" },
  { path: "/components/data-grid", heading: "DataGrid" },
  { path: "/components/descriptions", heading: "Descriptions" },
  { path: "/components/highlight", heading: "Highlight" },
  { path: "/components/image-list", heading: "ImageList" },
  { path: "/components/list", heading: "List" },
  { path: "/components/skeleton", heading: "Skeleton" },
  { path: "/components/spoiler", heading: "Spoiler" },
  { path: "/components/statistic", heading: "Statistic" },
  { path: "/components/table", heading: "Table" },
  { path: "/components/timeline", heading: "Timeline" },
  { path: "/components/tooltip", heading: "Tooltip" },
  { path: "/components/tree-view", heading: "TreeView" },
  { path: "/components/typography", heading: "Typography" },
  { path: "/components/affix", heading: "Affix" },
  { path: "/components/anchor", heading: "Anchor" },
  { path: "/components/app-shell", heading: "AppShell" },
  { path: "/components/aspect-ratio", heading: "AspectRatio" },
  { path: "/components/backdrop", heading: "Backdrop" },
  { path: "/components/badge", heading: "Badge" },
  { path: "/components/banner", heading: "Banner" },
  { path: "/components/alert", heading: "Alert" },
  { path: "/components/anchor", heading: "Anchor" },
  { path: "/components/bottom-navigation", heading: "BottomNavigation" },
  { path: "/components/breadcrumbs", heading: "Breadcrumbs" },
  { path: "/components/button-group", heading: "ButtonGroup" },
  { path: "/components/checkbox", heading: "Checkbox" },
  { path: "/components/chip", heading: "Chip" },
  { path: "/components/command-menu", heading: "CommandMenu" },
  { path: "/components/confirm-dialog", heading: "ConfirmDialog" },
  { path: "/components/container", heading: "Container" },
  { path: "/components/context-menu", heading: "ContextMenu" },
  { path: "/components/copy-button", heading: "CopyButton" },
  { path: "/components/dialog", heading: "Dialog" },
  { path: "/components/divider", heading: "Divider" },
  { path: "/components/drawer", heading: "Drawer" },
  { path: "/components/empty-state", heading: "EmptyState" },
  { path: "/components/button-group", heading: "ButtonGroup" },
  { path: "/components/checkbox", heading: "Checkbox" },
  { path: "/components/container", heading: "Container" },
  { path: "/components/field", heading: "Field" },
  { path: "/components/file", heading: "File" },
  { path: "/components/form", heading: "Form" },
  { path: "/components/grid", heading: "Grid" },
  { path: "/components/hover-card", heading: "HoverCard" },
  { path: "/components/input-group", heading: "InputGroup" },
  { path: "/components/kbd", heading: "Kbd" },
  { path: "/components/link", heading: "Link" },
  { path: "/components/loading-overlay", heading: "LoadingOverlay" },
  { path: "/components/menu", heading: "Menu" },
  { path: "/components/menubar", heading: "Menubar" },
  { path: "/components/navigation-menu", heading: "NavigationMenu" },
  { path: "/components/navbar", heading: "Navbar" },
  { path: "/components/number-input", heading: "NumberInput" },
  { path: "/components/page-header", heading: "PageHeader" },
  { path: "/components/pagination", heading: "Pagination" },
  { path: "/components/paper", heading: "Paper" },
  { path: "/components/password-input", heading: "PasswordInput" },
  { path: "/components/popover", heading: "Popover" },
  { path: "/components/progress", heading: "Progress" },
  { path: "/components/progress-ring", heading: "ProgressRing" },
  { path: "/components/radio-group", heading: "RadioGroup" },
  { path: "/components/result", heading: "Result" },
  { path: "/components/search-input", heading: "SearchInput" },
  { path: "/components/scroll-shadow", heading: "ScrollShadow" },
  { path: "/components/scroll-area", heading: "ScrollArea" },
  { path: "/components/select", heading: "Select" },
  { path: "/components/sheet", heading: "Sheet" },
  { path: "/components/sidebar", heading: "Sidebar" },
  { path: "/components/skip-link", heading: "SkipLink" },
  { path: "/components/slider", heading: "Slider" },
  { path: "/components/speed-dial", heading: "SpeedDial" },
  { path: "/components/spinner", heading: "Spinner" },
  { path: "/components/stack", heading: "Stack" },
  { path: "/components/splitter", heading: "Splitter" },
  { path: "/components/stepper", heading: "Stepper" },
  { path: "/components/switch", heading: "Switch" },
  { path: "/components/tabs", heading: "Tabs" },
  { path: "/components/toast", heading: "Toast" },
  { path: "/components/tour", heading: "Tour" },
  { path: "/components/text-field", heading: "TextField" },
  { path: "/components/textarea", heading: "Textarea" },
  { path: "/components/toggle-button", heading: "ToggleButton" },
  { path: "/components/visually-hidden", heading: "VisuallyHidden" },
  { path: "/components/fab", heading: "Fab" },
  { path: "/components/icon-button", heading: "IconButton" },
  { path: "/components/segmented-control", heading: "SegmentedControl" },
  { path: "/components/rating", heading: "Rating" },
  { path: "/components/combobox", heading: "Combobox" },
  { path: "/components/autocomplete", heading: "Autocomplete" },
  { path: "/components/multi-select", heading: "MultiSelect" },
  { path: "/components/otp-input", heading: "OtpInput" },
  { path: "/components/color-picker", heading: "ColorPicker" },
  { path: "/components/tag-input", heading: "TagInput" },
  { path: "/components/cascader", heading: "Cascader" },
  { path: "/components/tree-select", heading: "TreeSelect" },
  { path: "/components/transfer-list", heading: "TransferList" },
  { path: "/components/calendar", heading: "Calendar" },
  { path: "/components/date-picker", heading: "DatePicker" },
  { path: "/components/time-picker", heading: "TimePicker" },
  { path: "/components/date-time-picker", heading: "DateTimePicker" },
  { path: "/components/date-range-picker", heading: "DateRangePicker" },
  { path: "/components/line-chart", heading: "LineChart" },
  { path: "/components/bar-chart", heading: "BarChart" },
  { path: "/components/area-chart", heading: "AreaChart" },
  { path: "/components/pie-chart", heading: "PieChart" },
  { path: "/components/sparkline", heading: "Sparkline" },
  { path: "/components/gauge", heading: "Gauge" },
  { path: "/components/radar-chart", heading: "RadarChart" },
  { path: "/components/scatter-chart", heading: "ScatterChart" },
  { path: "/guides/theming", heading: "Theming" },
];

test("every docs page renders with no console errors", async ({ page }) => {
  const errors: string[] = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") errors.push(msg.text());
  });
  page.on("pageerror", (err) => errors.push(String(err)));

  for (const { path, heading } of pages) {
    const response = await page.goto(path);
    expect(response?.status(), path).toBe(200);
    await expect(page.getByRole("heading", { level: 1 }), path).toHaveText(heading);
    expect(errors, path).toEqual([]);
  }
});
